export enum ActivityAssets {
  Logo = 'https://cdn.rcd.gg/PreMiD/websites/U/Udemy/assets/logo.png',
}

export const UNKNOWN_COURSE = 'Unknown Course'
export const UNKNOWN_LECTURE = 'Unknown Lecture'
export const BROWSING_TIMESTAMP = Math.floor(Date.now() / 1000)
export const PATHNAMES: Record<string, string> = {
  '/': 'Homepage',
  '/affiliate': 'Udemy Affiliate',
  '/cart': 'Cart',
  '/course/create': 'Create a Course',
  '/dashboard/credit-history': 'Udemy Credits',
  '/dashboard/purchase-history': 'Purchase History',
  '/home/my-courses': 'My Courses',
  '/home/my-courses/archived': 'My Courses - Archived',
  '/home/my-courses/collections': 'My Courses - Collections',
  '/home/my-courses/learning': 'My Courses',
  '/home/my-courses/lists': 'My Courses - Lists',
  '/home/my-courses/search': 'My Courses - Search',
  '/home/my-courses/wishlist': 'My Courses - Wishlist',
  '/home/teaching/test-video': 'Test Video',
  '/instructor/account/api': 'API',
  '/instructor/account/close': 'Close Account',
  '/instructor/account/notifications': 'Account',
  '/instructor/account/security': 'Account Security',
  '/instructor/communication/announcements': 'Announcements',
  '/instructor/communication/assignments': 'Assignments',
  '/instructor/communication/messages': 'Messages',
  '/instructor/communication/qa': 'Q&A',
  '/instructor/courses': 'Create a Course',
  '/instructor/help': 'Resources',
  '/instructor/marketplace-insights': 'Marketplace Insights',
  '/instructor/performance/conversion/visitors': 'Visitors',
  '/instructor/performance/engagement': 'Engagement',
  '/instructor/performance/overview': 'Performance Overview',
  '/instructor/performance/reviews': 'Reviews',
  '/instructor/performance/students': 'Student Performance',
  '/instructor/tools': 'Tools',
  '/message': 'Messages',
  '/mobile': 'Udemy Mobile',
  '/support': 'Support',
  '/teaching': 'Teaching',
  '/user/close-account': 'Confirming Account Closure',
  '/user/edit-account': 'Editing Account Security Information',
  '/user/edit-api-clients': 'Editing API Clients',
  '/user/edit-photo': 'Editing Profile Picture',
  '/user/edit-profile': 'Editing Profile Information',
  '/user/edit-notification-preferences': 'Editing Notification Preferences',
  '/user/edit-payment-methods': 'Editing Payment Methods',
  '/user/edit-privacy': 'Editing Privacy Settings',
  '/user/manage-subscriptions': 'Managing Subscriptions',
  '/user/view-notifications': 'Notifications',
}
