export const rooms: Record<string, string> = {
  attic: 'https://i.imgur.com/dePRf4B.png',
  beach: 'https://i.imgur.com/bGClR4L.png',
  beacon: 'https://i.imgur.com/OXQb8kH.png',
  boiler: 'https://i.imgur.com/HCU5AIY.png',
  book: 'https://i.imgur.com/aA3BfOF.png',
  box: 'https://i.imgur.com/672dYj6.png',
  cave: 'https://i.imgur.com/nIulvbs.png',
  coffee: 'https://i.imgur.com/xVte6SY.png',
  court: 'https://i.imgur.com/4RjUzKB.png',
  cove: 'https://i.imgur.com/8mqRus5.png',
  dance: 'https://i.imgur.com/XiNiaGT.png',
  dock: 'https://i.imgur.com/aNG3D8c.png',
  dojo: 'https://i.imgur.com/Fqz3vhD.png',
  epf: 'https://i.imgur.com/ozRPu4r.png',
  forest: 'https://i.imgur.com/QMXPBkc.png',
  forts: 'https://i.imgur.com/IDUt1si.png',
  gift: 'https://i.imgur.com/9KxfTr3.png',
  hq: 'https://i.imgur.com/aZvd8Tx.png',
  iceberg: 'https://i.imgur.com/3nOej1L.png',
  lighthouse: 'https://i.imgur.com/5zdFBCq.png',
  lodge: 'https://i.imgur.com/5gWC5xt.png',
  lookout: 'https://i.imgur.com/iKdUDum.png',
  lounge: 'https://i.imgur.com/VaL1AvQ.png',
  mine: 'https://i.imgur.com/MoTRKQ0.png',
  ninja: 'https://i.imgur.com/ZwajrVt.png',
  office: 'https://i.imgur.com/y5DV2wv.png',
  old: 'https://i.imgur.com/XRPgCnJ.png',
  park: 'https://i.imgur.com/GWJQm65.png',
  pet: 'https://i.imgur.com/9t83lgH.png',
  pizza: 'https://i.imgur.com/QI5sjpR.png',
  plaza: 'https://i.imgur.com/xtQ8NtH.png',
  pond: 'https://i.imgur.com/40ggKNB.png',
  pool: 'https://i.imgur.com/j1KqTHt.png',
  recycle: 'https://i.imgur.com/V5a2I0X.png',
  shack: 'https://i.imgur.com/VGNMCRd.png',
  ski: 'https://i.imgur.com/H5R98De.png',
  sports: 'https://i.imgur.com/DUZwlrl.png',
  stadium: 'https://i.imgur.com/pWvAeBg.png',
  stage: 'https://i.imgur.com/usoi0xg.png',
  tourhq: 'https://i.imgur.com/KfGFJfJ.png',
  town: 'https://i.imgur.com/tfpUIuN.png',
  village: 'https://i.imgur.com/1fD7gKb.png',
  welcome: 'https://i.imgur.com/jUN2gyt.png',
}

export const icons: Record<string, string> = {
  main: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/logo.jpeg',
  igloo: 'https://i.imgur.com/diuVrIT.png',
  party: 'https://i.imgur.com/GpYszam.png',
  mission: 'https://i.imgur.com/ePS37kz.png',
}
