export const rooms: Record<string, string> = {
  attic: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/0.png',
  beach: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/1.png',
  beacon: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/2.png',
  boiler: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/3.png',
  book: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/4.png',
  box: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/5.png',
  cave: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/6.png',
  coffee: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/7.png',
  court: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/8.png',
  cove: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/9.png',
  dance: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/10.png',
  dock: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/11.png',
  dojo: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/12.png',
  epf: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/13.png',
  forest: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/14.png',
  forts: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/15.png',
  gift: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/16.png',
  hq: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/17.png',
  iceberg: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/18.png',
  lighthouse: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/19.png',
  lodge: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/20.png',
  lookout: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/21.png',
  lounge: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/22.png',
  mine: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/23.png',
  ninja: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/24.png',
  office: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/25.png',
  old: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/26.png',
  park: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/27.png',
  pet: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/28.png',
  pizza: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/29.png',
  plaza: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/30.png',
  pond: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/31.png',
  pool: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/32.png',
  recycle: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/33.png',
  shack: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/34.png',
  ski: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/35.png',
  sports: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/36.png',
  stadium: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/37.png',
  stage: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/38.png',
  tourhq: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/39.png',
  town: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/40.png',
  village: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/41.png',
  welcome: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/42.png',
}

export const icons: Record<string, string> = {
  main: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/logo.jpeg',
  igloo: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/43.png',
  party: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/44.png',
  mission: 'https://cdn.rcd.gg/PreMiD/websites/C/Club%20Penguin%20Journey/assets/45.png',
}
